#!/bin/bash



the_path="/mnt/c/Users/asus/tests"

# using for loop to create the 3 directories

for i in {1..3}
do
        dir_name="Directory_$i"
        dir_path="$the_path/$dir_name"

# check if the directory exists

if [ -d "$dir_path" ];
then
        echo "$dir_name is already exists"
else
        echo "$dir_name doesn't exists ...create it "
        mkdir $dir_path
fi


# using for loop to create the files inside each directory

for j in {1..2}
do
        file_name="file_$j.txt"
        file_path="$dir_name/$file_name"
# check if the file exists

if [ -f "$file_path" ];
then
        echo "$file_name is already exists"
else
        echo "$file_name doesn't exists creating...."
        touch $file_path
fi
done
done
